// q4-angular/src/app/components/navbar/navbar.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
    selector: 'app-navbar',
    templateUrl: './navbar.component.html',
    styleUrls: ['./navbar.component.scss']
})
export class NavbarComponent implements OnInit {

    public title = 'Reedsy Books';
    public isNavbarCollapsed = false;

    public links = [
        // { title: 'Home', url: 'home', active: true },
        { title: 'Books', url: 'books', active: true }
    ];

    constructor() { }

    ngOnInit() {
    }

    linkClicked(link: any) {
        this.links = this.links.map(d => {
            if (d.url === link.url) {
                d.active = true;
            } else {
                d.active = false;
            }
            return d;
        });
    }

}

// q4-vue/src/components/Navbar.vue
<template>
  <div>
    <b-navbar toggleable="lg" type="dark" variant="info">
      <b-navbar-brand :to="links[0].url" v-text="title">
      </b-navbar-brand>

      <b-navbar-toggle target="nav-collapse"></b-navbar-toggle>

      <b-collapse id="nav-collapse" is-nav>
        <b-navbar-nav>
            <template v-for="(link, i) of links">
                <b-nav-item :key="i" :to="link.url" :active="link.active" @click="linkClicked(link)">{{link.title}}
                </b-nav-item>
            </template>
        </b-navbar-nav>
      </b-collapse>
    </b-navbar>
  </div>
</template>

<script>
export default {
    name: "Navbar",
    data: () => ({
        title: 'Reedsy Books',
        links: [
            { title: 'Books', url: '/books', active: true }
        ]
    }),
    methods: {
        linkClicked(link) {
            this.links = this.links.map(d => {
                if (d.url === link.url) {
                    d.active = true;
                } else {
                    d.active = false;
                }
                return d;
            });
        }
    }
};
</script>
